openapi: 3.0.0
info:
  description: ThingsPro Edge OpenVPN
  version: 1.0.0
  title: ThingsPro Edge OpenVPN
tags:
  - name: settings
    description: openvpn settings
  - name: configuration
    description: openvpn client configuration
  # - name: DLM
  #   description: internal api for DLM
paths:
  /openvpn:
    get:
      tags:
        - settings
      operationId: getOvpnSettings
      description: |
        Get OpenVpn client setting
      responses:
        '200':
          description: get openvpn settings
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/OvpnSettings'
    put:
      tags:
        - settings
      description: |
        enable OpenVpn client with current profile file
      requestBody:
        required: true
        content:
            application/json:
              schema:
                type: object
                properties:
                  enable:
                    type: boolean
                    example: true
      responses:
        '200':
          description: enable openvpn client
        '400':
          description: 'invalid input, object invalid'

  /openvpn/profile:
    post:
      tags:
        - configuration
      operationId: getOvpnConfig
      description: |
        Import an OpenVpn client profile file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  example: 'client.ovpn'
      responses:
        '200':
          description: Import the client configuration file ok
    get:
      tags:
        - configuration
      operationId: exportOvpnConfig
      description: |
        Export current OpenVpn client profile file (get smaple config by qurey string)
      parameters:
      - in: query
        name: name
        description: sample
        schema:
          type: string
          example: "sample"
      responses:
        '200':
          description: Export the openvpn service settings ok
          content:
            multipart/form-data:
              schema:
                type: string
                format: binary
                example: 'client.ovpn'
        '400':
          description: 'invalid input, object invalid'
    delete:
      tags:
        - configuration
      description: |
        Delete Target OpenVpn client profile file
      responses:
        '200':
          description: set openvpn service settings ok
        '400':
          description: 'invalid input, object invalid'
  /openvpn/log:
    get:
      tags:
        - log
      description: |
        Export an OpenVpn client logs file
      responses:
        '200':
          description: Export the openvpn log ok
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 'invalid input, object invalid'
  /openvpn/dlm:
    patch:
      tags:
        - DLM
      description: |
        Patch DLM OpenVpn client setting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DLMOvpnSettings'
      responses:
        '200':
          description: set openvpn service settings ok
        '400':
          description: 'invalid input, object invalid'
components:
  examples:
    DLMSetting:
      value:
        data:
          enable: true
          profile: 'bW94YQ=='
    GeneralSetting:
      value:
        data:
          enable: true
          profile: 'client.ovpn'
  schemas:
    DLMOvpnSettings:
      type: object
      required:
        - enable
        - profile
      properties:
        type:
          type: string
          readOnly: true
          example: openvpn
        enable:
          type: boolean
          example: true
        status:
          type: string
          readOnly: true
          example: connected
          enum:
            - connected
            - disconnected
            - connecting
            - connect failed
        profile:
          type: string
          format: base64
          example: 'bW94YQ=='
        network:
          $ref: '#/components/schemas/OvpnNetwork'
    OvpnSettings:
      type: object
      required:
        - enable
        - profile
      properties:
        type:
          type: string
          readOnly: true
          example: openvpn
        enable:
          type: boolean
          example: true
        status:
          type: string
          readOnly: true
          example: connected
          enum:
            - connected
            - disconnected
            - connecting
            - connect failed
        ready:
          type: boolean
          readOnly: true
          example: true
        profile:
          type: string
          example: 'client.ovpn'
        network:
          $ref: '#/components/schemas/OvpnNetwork'
    OvpnNetwork:
      type: object
      properties:
        remoteIp:
          type: string
          format: ipaddress
          readOnly: true
          example: 10.144.48.22
        localIp:
          type: string
          readOnly: true
          example: 10.8.0.1
        netmask:
          type: string
          readOnly: true
          example: 255.255.255.0
        gateway:
          type: string
          readOnly: true
          example: 10.8.1.254